### ISSUE TITLE
How to use this in OCI

### ISSUE THREAD

**Issue by matheesha-pathirana** [sbatrow/DARKSSH-MANAGER#5]
I installed the program to the OCI Ubuntu instance and created some ssh accounts but they are not working, stuck at connecting.

**Comment by shakthilahiru** [comment]
iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT && iptables -P FORWARD ACCEPT && iptables -F && sudo netfilter-persistent save 

run this code on your VM instance

**Comment by sbatrow** [comment]
Tell me what cloud vps and ubuntu version you are using

**Comment by matheesha-pathirana** [comment]
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1013-oracle aarch64)

**Comment by sbatrow** [comment]
don't use Ubuntu 22.04.1. read [requerimientos](https://github.com/sbatrow/DARKSSH-MANAGER#heavy_exclamation_mark-requerimientos) plz. and oracle cloud need open port by hand VNC.

**Comment by matheesha-pathirana** [comment]
how do I open the port by hand VNC?
